### ISSUE TITLE
Rabbitmq api defaults  15_672 :confounded:

### ISSUE THREAD

**Issue by zerOnepal** [sensu-plugins/sensu-plugins-rabbitmq#12]
Its not a issue, but  lets stick to the default port... 
one line change here and it would save a lots of un-necessay lines and _issues post_ like this :wink: 

 I am talking about [these](https://github.com/sensu-plugins/sensu-plugins-rabbitmq/blob/master/bin/check-rabbitmq-queue.rb#L39) :neckbeard: 
```
option :port,
         description: 'RabbitMQ management API port',
         long: '--port PORT',
         proc: proc(&:to_i),
         default: 15_672
```

**Comment by tas50** [comment]
@zerOnepal I'm a bit confused.  What should the post be?  Isn't 15672 the default for RabbitMQ?

**Comment by zerOnepal** [comment]
yep @tas50, thanks for instant reply,

hmm, its my bad :see_no_evil:, we are converting it back with `proc: proc(&:to_i)`

but still I wonder so why we write **15_672** instead of 15672 on that default options...

**Comment by tas50** [comment]
The underscore is the preferred notation for Ruby numbers

**Comment by ryanvgates** [comment]
@tas50 Isn't it preferred [for clarity though](https://stackoverflow.com/a/4946411/299327)? I feel like it has the opposite effect with a port number. I would read it as "one, five, six, seven two" not "fifteen thousand six hundred and seventy two". I think it would make more sense if it was quantifying rather than identifying something.
